Admin: 
  tiFyPluginsForumTopicListTable:
    admin_menu:
      parent_slug:      'tiFyForum'
      menu_slug:        'tiFyForum'
      position:         1
    cb:               'tiFy\Plugins\Forum\Admin\Topic\ListTable\ListTable'
    edit_template:    'tiFyPluginsForumTopicEditForm'   
     
  tiFyPluginsForumTopicEditForm:
    admin_menu:
      parent_slug:      'tiFyForum'
      menu_slug:        'tiFyForumTopicEdit'
      position:         2
    cb:               'tiFy\Plugins\Forum\Admin\Topic\EditForm\EditForm'
          
Labels:
  plural:               "<?php _e( 'sujets', 'tify' );?>"
  singular:             "<?php _e( 'sujet', 'tify' );?>" 
  
Db:
  name:             'tify_forum_topic'
  install:          true
  col_prefix:       'topic_'
  meta:             true
  columns:
    id:
      type: BIGINT
      size: 20
      unsigned: true
      auto_increment: true
      
    author:
      type: BIGINT
      size: 20
      unsigned: true
      default: 0
    date:
      type: DATETIME
      default: 0000-00-00 00:00:00
      
    date_gmt:
      type: DATETIME
      default: 0000-00-00 00:00:00
      
    content:
      type: LONGTEXT
      search: true
      
    title:
      type: TEXT
      search: true
      
    excerpt:
      type: TEXT
      search: true
      
    status:
      type: VARCHAR
      size: 20
      default: publish
      
    contrib_status:
      type: VARCHAR
      size: 20
      default: open
      
    password:
      type: VARCHAR
      size: 20
      default: ""
      
    name:
      type: VARCHAR
      size: 200
      default: ""
      
    modified:
      type: DATETIME
      default: 0000-00-00 00:00:00
      
    modified_gmt:
      type: DATETIME
      default: 0000-00-00 00:00:00
      
    parent:
      type: BIGINT
      size: 20
      unsigned: true
      default: 0
      
    menu_order:
      type: INT
      size: 11
      default: 0
      
    contrib_count:
      type: BIGINT
      size: 20
      default: 0