Admin:
  tiFyPluginsForumContributorListUser:
    admin_menu:
      parent_slug:    'tiFyForum'
      menu_slug:      'tiFyForumContributorList'
      position:       5
    cb:             'tiFy\Plugins\Forum\Admin\Contributor\ListUser\ListUser'
    edit_template:  'tiFyPluginsForumContributorEditUser' 
    
  tiFyPluginsForumContributorEditUser:
    admin_menu:
      parent_slug:    'tiFyForum'
      menu_slug:      'tiFyForumContributorEdit'
      position:       6
    cb:             'tiFy\Plugins\Forum\Admin\Contributor\EditUser\EditUser'
          
Labels:
  plural:               "<?php _e( 'contributeurs', 'tify' );?>"
  singular:             "<?php _e( 'contributeur', 'tify' );?>"  